### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by HyogoMoura** [HyogoMoura/GCMS-Diogo-Moura#1]
@ramidedantas

- [ ] Install git localy
- [ ] Create local project 
- [ ] Create local git repository and peform first commit
- [ ] Push updates for the remote repository
- [ ] Update class repository
